### PR TITLE
Fix undefined methods errors for class ApplicationController

### PR DESCRIPTION
**Pull request by MorganFujimaka**

### CODE REVIEW

**Comment by seanpdoyle** [comment]
Thanks for submitting this patch!

Could you provide some more context about what motivated this PR?

**Comment by MorganFujimaka** [comment]
Actually now I'm not sure this fix is correct and I'm going to decline it. Here is more details I should've provided. When I install v0.5.0 or later and run `rails generate ember-cli:init` I face `/app/controllers/application_controller.rb:8:in `alias_method': undefined method `authenticate_user!' for class `ApplicationController' (NameError)`. v0.4.3 works fine.

**Comment by seanpdoyle** [comment]
@MorganFujimaka thanks for some more background!

It sounds like you're using Devise or another authentication gem that is affecting this gem somehow.

Would you be able to share a minimal code sample that reproduces this bug?

**Comment by seanpdoyle** [comment]
@MorganFujimaka Would you be able to share a minimal code sample that reproduces this bug?

I'll close this PR until we can get some more information.

**Comment by allthesignals** [comment]
Hi @seanpdoyle 

We're seeing the same issue. Error message is a little different (happy to provide full stack trace if needed):
``alias_method': undefined method `current_user' for class `ApplicationController' (NameError)`

Here's some code sample:

```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate_user!(options = {})
    if user_signed_in?
      super
    else
      redirect_to '/users/sign_in'
    end
  end

  alias_method :devise_current_user, :current_user

  def current_user
    UserPresenter.new(devise_current_user)
  end

end
```

We're using devise (3.5.6) and ember-cli-rails (0.7.2).

**Comment by seanpdoyle** [comment]
@allthesignals judging by your code snippet, the error:

```
alias_method': undefined methodcurrent_user' for class ApplicationController' (NameError)
```

 seems unrelated to `ember-cli-rails`. 

[alias_method](http://ruby-doc.org/core-2.2.2/Module.html#method-i-alias_method) is defined at the Ruby level, so I'm not sure what would cause `ember-cli-rails` to interfere with it.

> happy to provide full stack trace if needed

Could you please share the stack trace?

**Comment by allthesignals** [comment]
Possibly, but without the `ember-cli-rails` installed, all tests pass and I'm able to run `rails s`.  As a temporary fix, I forked and made the same change @MorganFujimaka proposed with success.

Stack trace:
```
/source/developmentdatabase/app/controllers/application_controller.rb:16:in `alias_method': undefined method `current_user' for class `ApplicationController' (NameError)
	from /source/developmentdatabase/app/controllers/application_controller.rb:16:in `<class:ApplicationController>'
	from /source/developmentdatabase/app/controllers/application_controller.rb:1:in `<top (required)>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/ember-cli-rails-0.7.2/app/controller/ember_cli/ember_controller.rb:2:in `<module:EmberCli>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/ember-cli-rails-0.7.2/app/controller/ember_cli/ember_controller.rb:1:in `<top (required)>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/ember-cli-rails-0.7.2/lib/ember_cli/engine.rb:4:in `block in <class:Engine>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/mgardner/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /source/developmentdatabase/config/environment.rb:5:in `<top (required)>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /source/developmentdatabase/config.ru:3:in `block in <main>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /source/developmentdatabase/config.ru:in `new'
	from /source/developmentdatabase/config.ru:in `<main>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /source/developmentdatabase/bin/rails:9:in `require'
	from /source/developmentdatabase/bin/rails:9:in `<top (required)>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from /Users/mgardner/.rvm/gems/ruby-2.1.5@dd/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /source/developmentdatabase/bin/spring:13:in `require'
	from /source/developmentdatabase/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Pull request closed without merging**
