### PR TITLE
Disable SelectorFormat for hound

### PR DESCRIPTION
**Pull request by jasonramirez**
When using BEM, Hound complains about everything. I am attempting to
completely disable the NameFormat because I have not found a convention
that works with BEM.

### CODE REVIEW

**Comment by ethangl** [comment]
:boom:

**Comment by seanpdoyle** [comment]
:+1:

**Comment by seanpdoyle** [comment]
@jasonramirez would you mind closing this PR and moving the code changes to your branch? 

That way, on the next push of new styles we can verify that Hound ignores your BEM.

**Comment by tysongach** [comment]
@jasonramirez FWIW, here’s my standard scss-lint settings (which I use with BEM): https://github.com/tysongach/dotfiles-local/blob/master/scss-lint.yml

**Comment by seanpdoyle** [comment]
@jasonramirez was this handled elsewhere?

Could we close this?

**Comment by seanpdoyle** [comment]
@jasonramirez what's the status on this PR? Will we be moving forward with this or is it safe to close and delete?

**Comment by seanpdoyle** [comment]
@jasonramirez I'm closing and deleting this branch.

If you still need to merge this, please re-push and reopen.

**Pull request closed without merging**
