### PR TITLE
updated readme with performance related information

### PR DESCRIPTION
**Pull request by mreinsch**

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@mreinsch thanks for these changes!

I'll try out your suggestions on a project of mine to verify that they work well. Once that's done, I'll merge this in.

**Comment by seanpdoyle** [comment]
Merged in https://github.com/thoughtbot/ember-cli-rails/commit/4f3b7c00dd936b65e4824cc910b01c592a7ebf00.

Thanks!

**Comment by harisadam** [comment]
@seanpdoyle i think you closed a wrong PR :)

**Comment by seanpdoyle** [comment]
@harisadam I sure did, thanks for bringing this to my attention!

**Comment by seanpdoyle** [comment]
@mreinsch could you explain the importance of the calls to `npm prune` and `bower prune`?

**Comment by mreinsch** [comment]
Thanks for looking into my changes.

The prune parts will remove any old packages which aren't needed anymore. As Heroku is now caching all installed npm and bower packages this is necessary, otherwise obsolete packages will just never get removed.

**Comment by seanpdoyle** [comment]
@mreinsch the Heroku portion of this PR has been resolved by https://github.com/thoughtbot/ember-cli-rails/commit/398852fac53099b88a6d8e86e4b2b32a9f332d6e,

please give that a shot!

I'd love to learn more about the the Source maps portion. Could you provide some more context around your findings?

**Comment by seanpdoyle** [comment]
I think the generator and the [Heroku](https://github.com/thoughtbot/ember-cli-rails#heroku) section of the README covers this.

Would you mind opening an issue / PR explaining how to reproduce the errors you've seen in the latter part about the `.map` files?

**Pull request closed without merging**
